[project]
output = "output"
template = "templates/global.html"

[[sources]]
input = "pages/**/*.html"
strip_prefix = "pages/"

# [[sources]]
# input = "blog/**/*.html"
# template = "templates/blog-post.html"
# hierarchy.parent = "file://./pages/blog.html"
